theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

title: Eric Pihlstrom
description: Welcome to my website!
show_downloads: false
